REFERENCE_GENOME = 'GRCh38'

[IMPORT]

MAPPING_FILE = "/mnt/project/data/misc/mappings_with_blocks.tsv"
INTERVAL_FILE = "/mnt/project/data/misc/xgen_plus_spikein.b38.bed"
VCF_DIR = "/mnt/project/Bulk/Exome sequences/Population level exome OQFE variants, pVCF format"
GENE_FILE = "../genes.txt"
LOG_DIR = "../hail_logs/"
VCF_VERSION = "v1"
DATABASE = "matrix_tables"
# DOWNSAMPLE_P = 0.005

[ANNOTATE]
SNV_ONLY = true
USE_VEP = true
VEP_JSON = "/mnt/project/data/misc/GRCh38_VEP.json"
MISSENSE_ONLY = true
ANNOTATION_DIR = "annotations/"

[SAMPLE_QC]
UKB_REL_DAT_FILE = "Bulk/Genotype Results/Genotype calls/ukb_rel.dat"
SAMPLE_FILTER_FILE = "samples_to_remove.tsv"
DATA_DIR = "/mnt/project/data/processed"
MAX_KINSHIP = 0.088
MIN_CALL_RATE = 0.95
MIN_MEAN_DP = 15
MIN_MEAN_GQ = 50

[VARIANT_QC]
MIN_P_HWE = 10e-15
MIN_VAR_GQ = 20

[ENTRY_QC]
MIN_DP = 10
MIN_GQ = 20
MIN_PL = 20

[EXPORT]
TMP_DIR = "../tmp"